name: familyai
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: any
  flutter_bloc: 8.1.6
  qlevar_router: 1.10.0
  jiffy: ^6.3.1
  get_it: 7.7.0
  firebase_auth: 5.1.2
  logger:
  flutter_svg: 2.0.10+1
  cached_network_image: 3.3.1
  image_picker: 1.1.2
  skeletonizer: ^1.3.0
  dio: ^5.5.0+1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  audio_waveforms: ^1.0.5
  rxdart: ^0.27.7
  json_serializable: ^6.8.0
  uuid: ^4.4.0
  flutter_inappwebview: ^6.0.0
  device_info_plus: ^10.1.0
  web_socket_channel: ^3.0.1
  image: ^4.2.0
  flutter_html: ^3.0.0-beta.2
  flutter_markdown: ^0.7.3+1
  firebase_core: 3.4.0
  flutter_webrtc: 0.11.7
  firebase_crashlytics: 4.1.0
  firebase_remote_config: 5.1.0
  google_sign_in: ^6.2.1
  url_launcher: ^6.3.0
dependency_overrides:
  http: ^1.0.0
  web: ^1.0.0

  # TODO: Recheck once flutter_inappwebview version >6.0.0 is released
  flutter_inappwebview_android:
    git:
      url: https://github.com/holzgeist/flutter_inappwebview
      path: flutter_inappwebview_android
      ref: d89b1d32638b49dfc58c4b7c84153be0c269d057

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: any
  flutter_gen_runner: any
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Kumbh
      fonts:
        - asset: assets/fonts/kumbh/KumbhSans-Regular.ttf
        - asset: assets/fonts/kumbh/KumbhSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/kumbh/KumbhSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/kumbh/KumbhSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/kumbh/KumbhSans-Black.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/inter_regular.ttf
        - asset: assets/fonts/inter/inter_regular.ttf
          weight: 400
        - asset: assets/fonts/inter/inter_medium.ttf
          weight: 500
        - asset: assets/fonts/inter/inter_bold.ttf
          weight: 600
        - asset: assets/fonts/inter/inter_black.ttf
          weight: 700
    - family: Oddval
      fonts:
        - asset: assets/fonts/oddval/oddval-regular.otf
        - asset: assets/fonts/oddval/oddval-regular.otf
          weight: 400
        - asset: assets/fonts/oddval/oddval-medium.otf
          weight: 500
        - asset: assets/fonts/oddval/oddval-bold.otf
          weight: 600
        - asset: assets/fonts/oddval/oddval-black.otf
          weight: 700
flutter_gen:
  integrations:
    flutter_svg: true
